input1 = int(input("첫번째 숫자를 입력하세요: "))
input2 = int(input("두번째 숫자를 입력하세요: "))
print(f"{input1} + {input2} = {input1 + input2}")
print(f"{input1} - {input2} = {input1 - input2}")
print(f"{input1} * {input2} = {input1 * input2}")
print(f"{input1} / {input2} = {input1 / input2}")